#默认使用配置
spring:
  profiles:
    active: #spring.profiles.active#
  servlet:
      multipart:
          max-file-size: 100MB
          max-request-size: 100MB
          enabled: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  tomcat:
    uri-encoding: UTF-8
  
#mybatis
mybatis-plus:
  mapper-locations: xml/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lunz.cpfw.web.entities
  #逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#mybatis-plus配置控制台打印完整带参数SQL语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
